PROFILENAME=UAT
MNELOGONURL=https://bkrmvxm3.bangkokranch.com:22008/mne/servlet/MvxMCSvt
APPPORT=16305
APPSERVER=192.200.9.190
DBNAME=BRLDTABK01
DBM3NAME=M3FDBTST
WORKFLOW=https://workflow.br-bangkokranch.com/webhook/tst/service-request
CHECKTOKENURL=http://192.200.9.94:8080/authen_api/auth/checktoken
GENTOKENURL=http://192.200.9.94:8080/authen_api/auth/gentoken
GENTOKENWOTOKENURL=http://192.200.9.94:8080/authen_api/auth/gentokenwotoken
