PROFILENAME=PRD
MNELOGONURL=https://bkrmvxm3.bangkokranch.com:21008/mne/servlet/MvxMCSvt
APPPORT=16105
APPSERVER=192.200.9.190
DBNAME=BRLDTA0100
DBM3NAME=M3FDBPRD
WORKFLOW=https://workflow.br-bangkokranch.com/webhook/service-request
CHECKTOKENURL=https://service.br-bangkokranch.com/authen_api/auth/v2/checktoken
GENTOKENURL=https://service.br-bangkokranch.com/authen_api/auth/v2/gentoken
GENTOKENWOTOKENURL=https://service.br-bangkokranch.com/authen_api/auth/v2/gentokenwotoken
