## Eureka Server
eureka.serviceUrl.default=http://localhost:8761/eureka/
eureka.preferSameZone=false
eureka.shouldUseDns=false

## Application Instance
eureka.name=SERVICEREQUEST-API
eureka.vipAddress=SERVICEREQUEST-API
eureka.port=8080

## Registration
eureka.registration.enabled=true
eureka.registryFetchIntervalSeconds=30
eureka.leaseRenewalIntervalInSeconds=5
eureka.leaseExpirationDurationInSeconds=10
